version: '2'
services:
    hbinspayplatform-app:
        image: hbinspayplatform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@hbinspayplatform-oracle:1521:hbinsPayPlatform
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 7601:7601
